version: '3.4'

services:
  flutter:
    image: "flutter_wms_app"
    build: 
        context: .
        dockerfile: Dockerfile
    volumes: 
        - ./wms_apk/:/app/build/app/outputs/flutter-apk

      
